# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0002_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='shipping',
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
