# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-01 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0004_auto_20180301_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
