# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-02 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0004_auto_20180302_0207'),
        ('eCommerce', '0005_auto_20180301_2243'),
        ('eCommerce', '0005_auto_20180301_2253'),
    ]

    operations = [
    ]
