# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-02 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0006_merge_20180302_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='security_code',
        ),
        migrations.AddField(
            model_name='customer',
            name='stripe_customer',
            field=models.CharField(default='', max_length=255),
        ),
    ]
